- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.3dmet.dna.affrc.go.jp'', port=80): Max retries
    exceeded with url: /cgi/show_data.php?acc=B00162 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f37b310>, ''Connection to www.3dmet.dna.affrc.go.jp timed out. (connect
    timeout=15)''))'
  example: B00162
  message: ConnectTimeout
  name: 3D Metabolites
  prefix: 3dmet
  url: http://www.3dmet.dna.affrc.go.jp/cgi/show_data.php?acc=B00162
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: T0599
  message: HTTP 403
  name: Applied Biological Materials cell line products
  prefix: abm
  url: https://www.abmgood.com/catalogsearch/result/?cat=&q=T0599
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: C0020004/4992
  message: HTTP 404
  name: AddexBio cell line products
  prefix: addexbio
  url: https://www.addexbio.com/productdetail?pid=C0020004/4992
- contact_email: alpha.tom.kodamullil@scai.fraunhofer.de
  contact_github: akodamullil
  contact_name: Alpha Tom Kodamullil
  context: '500'
  example: '0000001'
  message: HTTP 500
  name: Alzheimer's Disease Ontology
  prefix: ado
  url: http://purl.obolibrary.org/obo/ADO_0000001
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''wasabi.lutzonilab.net'', port=80): Max retries
    exceeded with url: /pub/displayTaxonInfo?aftol_id=959 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f359f10>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '959'
  message: ConnectionError
  name: Assembling the Fungal Tree of Life - Taxonomy
  prefix: aftol.taxonomy
  url: http://wasabi.lutzonilab.net/pub/displayTaxonInfo?aftol_id=959
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''ontology.apa.org'', port=80): Max retries exceeded
    with url: /apaonto/termsonlyOUT%20(5).owl (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f37bc10>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: Abdomen
  message: ConnectionError
  name: Psychology Ontology
  prefix: apaonto
  url: http://ontology.apa.org/apaonto/termsonlyOUT%20(5).owl#Abdomen
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''aps.unmc.edu'', port=80): Max retries exceeded
    with url: /AP/database/query_output.php?ID=01001 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f0ff9d0>: Failed to establish a new connection: [Errno 61] Connection
    refused''))'
  example: '01001'
  message: ConnectionError
  name: Antimicrobial Peptide Database
  prefix: apd
  url: http://aps.unmc.edu/AP/database/query_output.php?ID=01001
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''bipaa.genouest.org'', port=80): Max retries
    exceeded with url: /apps/grs-2.3/grs?reportID=aphidbase_transcript_report&objectID=ACYPI000159
    (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x11f0ffb80>:
    Failed to establish a new connection: [Errno 61] Connection refused''))'
  example: ACYPI000159
  message: ConnectionError
  name: AphidBase Transcript
  prefix: aphidbase.transcript
  url: http://bipaa.genouest.org/apps/grs-2.3/grs?reportID=aphidbase_transcript_report&objectID=ACYPI000159
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: P01116
  message: HTTP 500
  name: APID Interactomes
  prefix: apid.interactions
  url: http://cicblade.dep.usal.es:8080/APID/Interactions.action?protein=P01116
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.arachnoserver.org'', port=80): Max retries
    exceeded with url: /toxincard.html?id=AS000060 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f3c3f10>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: AS000060
  message: ConnectionError
  name: ArachnoServer
  prefix: arachnoserver
  url: http://www.arachnoserver.org/toxincard.html?id=AS000060
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: CAE46076
  message: HTTP 404
  name: Antibiotic Resistance Genes Database
  prefix: ardb
  url: http://ardb.cbcb.umd.edu/cgi/search.cgi?db=L&amp;field=ni&amp;term=CAE46076
- contact_email: null
  contact_github: null
  contact_name: null
  context: '525'
  example: icdom:8500_3
  message: HTTP 525
  name: ArrayMap
  prefix: arraymap
  url: https://www.arraymap.org/pgx:icdom:8500_3
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: 0471491039
  message: HTTP 404
  name: Amazon Standard Identification Number
  prefix: asin
  url: https://amzn.com/0471491039
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.aspergillusgenome.org'', port=80): Max retries
    exceeded with url: /cgi-bin/locus.pl?dbid=ASPL0000349247 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f36b7c0>, ''Connection to www.aspergillusgenome.org timed out. (connect
    timeout=15)''))'
  example: ASPL0000349247
  message: ConnectTimeout
  name: Aspergillus Genome Database
  prefix: aspgd.locus
  url: http://www.aspergillusgenome.org/cgi-bin/locus.pl?dbid=ASPL0000349247
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.aspergillusgenome.org'', port=80): Max retries
    exceeded with url: /cgi-bin/protein/proteinPage.pl?dbid=ASPL0000349247 (Caused
    by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f105d90>,
    ''Connection to www.aspergillusgenome.org timed out. (connect timeout=15)''))'
  example: ASPL0000349247
  message: ConnectTimeout
  name: AspGD Protein
  prefix: aspgd.protein
  url: http://www.aspergillusgenome.org/cgi-bin/protein/proteinPage.pl?dbid=ASPL0000349247
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: CUT
  message: HTTP 404
  name: Animal TFDB Family
  prefix: atfdb.family
  url: http://www.bioguo.org/AnimalTFDB/family.php?fam=CUT
- contact_email: rlwalls2008@gmail.com
  contact_github: ramonawalls
  contact_name: Ramona Walls
  context: '404'
  example: 0000081
  message: HTTP 404
  name: Biological Collections Ontology
  prefix: bco
  url: http://purl.obolibrary.org/obo/BCO_0000081
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''beetlebase.org'', port=80): Max retries exceeded
    with url: /cgi-bin/gbrowse/BeetleBase3.gff3/?name=TC010103 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f3c38e0>, ''Connection to beetlebase.org timed out. (connect timeout=15)''))'
  example: TC010103
  message: ConnectTimeout
  name: Tribolium Genome Database -- Insertion
  prefix: beetlebase
  url: http://beetlebase.org/cgi-bin/gbrowse/BeetleBase3.gff3/?name=TC010103
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cgap.nci.nih.gov'', port=443): Max retries
    exceeded with url: /Pathways/BioCarta/h_aktPathway (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection
    object at 0x11f3d3910>, ''Connection to cgap.nci.nih.gov timed out. (connect timeout=15)''))'
  example: h_aktPathway
  message: ConnectTimeout
  name: BioCarta Pathway
  prefix: biocarta.pathway
  url: https://cgap.nci.nih.gov/Pathways/BioCarta/h_aktPathway
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '614'
  message: HTTP 403
  name: BioCatalogue Service
  prefix: biocatalogue.service
  url: https://www.biocatalogue.org/services/614
- contact_email: null
  contact_github: null
  contact_name: null
  context: '502'
  example: aef4c195-9cf9-46db-a12a-7cfd1ff3eec3
  message: HTTP 502
  name: Bio-MINDER Tissue Database
  prefix: biominder
  url: https://datalab.rwth-aachen.de/MINDER/resource/aef4c195-9cf9-46db-a12a-7cfd1ff3eec3
- contact_email: null
  contact_github: null
  contact_name: null
  context: '415'
  example: BIOMD0000000048
  message: HTTP 415
  name: BioModels Database
  prefix: biomodels.db
  url: https://www.ebi.ac.uk/biomodels/BIOMD0000000048
- contact_email: jonrkarr@gmail.com
  contact_github: jonrkarr
  contact_name: Jonathan Karr
  context: 'HTTPSConnectionPool(host=''www.biomodels.net'', port=443): Max retries
    exceeded with url: /kisao/KISAO (Caused by SSLError(CertificateError("hostname
    ''www.biomodels.net'' doesn''t match either of ''www4.ebi.ac.uk'', ''www.www4.ebi.ac.uk''")))'
  example: '0000057'
  message: SSLError
  name: Kinetic Simulation Algorithm Ontology
  prefix: biomodels.kisao
  url: https://www.biomodels.net/kisao/KISAO#KISAO_0000057
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '001'
  message: HTTP 404
  name: BioSystems
  prefix: biosystems
  url: https://www.ncbi.nlm.nih.gov/biosystems/001
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''bitterdb.agri.huji.ac.il'', port=443): Max
    retries exceeded with url: /bitterdb/compound.php?id=46 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: '46'
  message: SSLError
  name: BitterDB Compound
  prefix: bitterdb.cpd
  url: http://bitterdb.agri.huji.ac.il/bitterdb/compound.php?id=46
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''bitterdb.agri.huji.ac.il'', port=443): Max
    retries exceeded with url: /Receptor.php?id=1 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: '1'
  message: SSLError
  name: BitterDB Receptor
  prefix: bitterdb.rec
  url: http://bitterdb.agri.huji.ac.il/Receptor.php?id=1
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '15000'
  message: HTTP 404
  name: Biological Magnetic Resonance Data Bank
  prefix: bmrb
  url: http://rest.bmrb.wisc.edu/bmrb/15000/html
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: 1.1.1.1
  message: HTTP 403
  name: BRENDA, The Comprehensive Enzyme Information System
  prefix: brenda
  url: https://www.brenda-enzymes.org/php/result_flat.php4?ecno=1.1.1.1
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '278'
  message: HTTP 403
  name: BRENDA Ligand
  prefix: brenda.ligand
  url: https://www.brenda-enzymes.de/ligand.php?brenda_ligand_id=278
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '18030'
  message: HTTP 403
  name: BRENDA Ligand Group
  prefix: brenda.ligandgroup
  url: https://www.brenda-enzymes.de/ligand.php?brenda_group_id=18030
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''bugs.sgul.ac.uk'', port=80): Max retries exceeded
    with url: /bugsbase/tabs/experiment.php?expt_id=288&action=view (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f3f2b20>, ''Connection to bugs.sgul.ac.uk timed out. (connect timeout=15)''))'
  example: '288'
  message: ConnectTimeout
  name: BugBase Expt
  prefix: bugbase.expt
  url: http://bugs.sgul.ac.uk/bugsbase/tabs/experiment.php?expt_id=288&action=view
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''bugs.sgul.ac.uk'', port=80): Max retries exceeded
    with url: /bugsbase/tabs/protocol.php?protocol_id=67&amp;action=view (Caused by
    ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f3f22e0>,
    ''Connection to bugs.sgul.ac.uk timed out. (connect timeout=15)''))'
  example: '67'
  message: ConnectTimeout
  name: BugBase Protocol
  prefix: bugbase.protocol
  url: http://bugs.sgul.ac.uk/bugsbase/tabs/protocol.php?protocol_id=67&amp;action=view
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''bykdb.ibcp.fr'', port=443): Max retries exceeded
    with url: /data/html/annotated/A0A009E7X8.html (Caused by SSLError(CertificateError("hostname
    ''bykdb.ibcp.fr'' doesn''t match either of ''npsa-prabi.ibcp.fr'', ''npsa-pbil.ibcp.fr''")))'
  example: A0A009E7X8
  message: SSLError
  name: Bacterial Tyrosine Kinase Database
  prefix: bykdb
  url: https://bykdb.ibcp.fr/data/html/annotated/A0A009E7X8.html
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''webprod3.hc-sc.gc.ca'', port=80): Max retries
    exceeded with url: /dpd-bdpp/info.do?lang=eng&code=63250 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f3f2640>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '63250'
  message: ConnectionError
  name: Canadian Drug Product Database
  prefix: cdpd
  url: http://webprod3.hc-sc.gc.ca/dpd-bdpp/info.do?lang=eng&code=63250
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: ab-1-ha
  message: HTTP 404
  name: CellBank Australia
  prefix: cellbank.australia
  url: https://www.cellbankaustralia.com/ab-1-ha.html
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.cghtmd.jp'', port=443): Max retries exceeded
    with url: /CNVDatabase?hid=300165/p13898_2106T&aid=%2525t&lang=en (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has
    expired (_ssl.c:1129)'')))'
  example: 300165/p13898_2106T
  message: SSLError
  name: CGH Data Base
  prefix: cghdb
  url: http://www.cghtmd.jp/CGHDatabase/mapViewer?hid=300165/p13898_2106T&aid=%t&lang=en
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: CH_001923
  message: HTTP 404
  name: CharProt
  prefix: charprot
  url: http://www.jcvi.org/charprotdb/index.cgi/view/CH_001923
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: 300108/p3934_A-172
  message: HTTP 404
  name: Cell Lines Service
  prefix: cls
  url: https://cls.shop/300108/p3934_A-172
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cmecscatalog.org'', port=443): Max retries
    exceeded with url: /cmecs/classification/unit/595.html (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f40abb0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '595'
  message: ConnectionError
  name: Costal and Marine Ecological Classification Standard
  prefix: cmecs
  url: https://cmecscatalog.org/cmecs/classification/unit/595.html
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_320:0000618 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3b86a0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000618
  message: ConnectionError
  name: Rice ontology
  prefix: co_320
  url: https://www.cropontology.org/rdf/CO_320:0000618
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_321:0000449 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3d3700>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000449
  message: ConnectionError
  name: Wheat ontology
  prefix: co_321
  url: https://www.cropontology.org/rdf/CO_321:0000449
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_322:0000773 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f0f7ee0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000773'
  message: ConnectionError
  name: Maize ontology
  prefix: co_322
  url: https://www.cropontology.org/rdf/CO_322:0000773
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_323:0000252 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3ff460>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000252'
  message: ConnectionError
  name: Barley ontology
  prefix: co_323
  url: https://www.cropontology.org/rdf/CO_323:0000252
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_324:0000111 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3c3d60>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000111'
  message: ConnectionError
  name: Sorghum ontology
  prefix: co_324
  url: https://www.cropontology.org/rdf/CO_324:0000111
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_325:0000519 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3c3220>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000519
  message: ConnectionError
  name: Banana ontology
  prefix: co_325
  url: https://www.cropontology.org/rdf/CO_325:0000519
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_327:0000095 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3b8a60>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000095
  message: ConnectionError
  name: Pearl millet ontology
  prefix: co_327
  url: https://www.cropontology.org/rdf/CO_327:0000095
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_330:0000106 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f0edbe0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000106'
  message: ConnectionError
  name: Potato ontology
  prefix: co_330
  url: https://www.cropontology.org/rdf/CO_330:0000106
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_331:0000088 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f1268e0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000088
  message: ConnectionError
  name: Sweet Potato ontology
  prefix: co_331
  url: https://www.cropontology.org/rdf/CO_331:0000088
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_333:3000045 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f1b5d60>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '3000045'
  message: ConnectionError
  name: Beet Ontology ontology
  prefix: co_333
  url: https://www.cropontology.org/rdf/CO_333:3000045
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_334:0000070 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3c37c0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000070'
  message: ConnectionError
  name: Cassava ontology
  prefix: co_334
  url: https://www.cropontology.org/rdf/CO_334:0000070
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_335:0000189 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3f2640>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000189
  message: ConnectionError
  name: Common Bean ontology
  prefix: co_335
  url: https://www.cropontology.org/rdf/CO_335:0000189
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_336:0000339 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3ffeb0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000339
  message: ConnectionError
  name: Soybean ontology
  prefix: co_336
  url: https://www.cropontology.org/rdf/CO_336:0000339
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_337:0000054 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f1266d0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000054'
  message: ConnectionError
  name: Groundnut ontology
  prefix: co_337
  url: https://www.cropontology.org/rdf/CO_337:0000054
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_338:0000138 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f1362b0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000138
  message: ConnectionError
  name: Chickpea ontology
  prefix: co_338
  url: https://www.cropontology.org/rdf/CO_338:0000138
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_339:0000032 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f19f6d0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000032'
  message: ConnectionError
  name: Lentil ontology
  prefix: co_339
  url: https://www.cropontology.org/rdf/CO_339:0000032
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_340:0000639 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3d3670>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000639
  message: ConnectionError
  name: Cowpea ontology
  prefix: co_340
  url: https://www.cropontology.org/rdf/CO_340:0000639
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_341:0000140 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f136190>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000140'
  message: ConnectionError
  name: Pigeonpea ontology
  prefix: co_341
  url: https://www.cropontology.org/rdf/CO_341:0000140
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_343:0100010 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3b8f70>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0100010'
  message: ConnectionError
  name: Yam ontology
  prefix: co_343
  url: https://www.cropontology.org/rdf/CO_343:0100010
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_345:0000127 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3b8a60>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000127'
  message: ConnectionError
  name: Brachiaria ontology
  prefix: co_345
  url: https://www.cropontology.org/rdf/CO_345:0000127
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_346:0000199 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3b8d30>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000199
  message: ConnectionError
  name: Mungbean ontology
  prefix: co_346
  url: https://www.cropontology.org/rdf/CO_346:0000199
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_347:0000108 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3ffa90>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000108
  message: ConnectionError
  name: Castor bean ontology
  prefix: co_347
  url: https://www.cropontology.org/rdf/CO_347:0000108
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_348:1100107 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3ff550>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '1100107'
  message: ConnectionError
  name: Brassica ontology
  prefix: co_348
  url: https://www.cropontology.org/rdf/CO_348:1100107
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_350:0000215 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f144130>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000215'
  message: ConnectionError
  name: Oat ontology
  prefix: co_350
  url: https://www.cropontology.org/rdf/CO_350:0000215
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_356:4000027 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3ff9a0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '4000027'
  message: ConnectionError
  name: Vitis ontology
  prefix: co_356
  url: https://www.cropontology.org/rdf/CO_356:4000027
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_357:1000290 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f144340>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '1000290'
  message: ConnectionError
  name: Woody Plant Ontology ontology
  prefix: co_357
  url: https://www.cropontology.org/rdf/CO_357:1000290
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_358:0000139 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f144b20>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000139
  message: ConnectionError
  name: Cotton ontology
  prefix: co_358
  url: https://www.cropontology.org/rdf/CO_358:0000139
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_359:0000947 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f1c5d60>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: 0000947
  message: ConnectionError
  name: Sunflower ontology
  prefix: co_359
  url: https://www.cropontology.org/rdf/CO_359:0000947
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_360:0000071 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f126a90>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000071'
  message: ConnectionError
  name: Sugar Kelp trait ontology
  prefix: co_360
  url: https://www.cropontology.org/rdf/CO_360:0000071
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_365:0000205 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3ffbb0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000205'
  message: ConnectionError
  name: Fababean ontology
  prefix: co_365
  url: https://www.cropontology.org/rdf/CO_365:0000205
- contact_email: helpdesk@cropontology-curationtool.org
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''cropontology.orgrdf'', port=443): Max retries
    exceeded with url: /CO_366:0000072 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f19f5b0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '0000072'
  message: ConnectionError
  name: Bambara groundnut ontology
  prefix: co_366
  url: https://www.cropontology.org/rdf/CO_366:0000072
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.flymine.org'', port=443): Read timed out.
    (read timeout=15)'
  example: MOL000160
  message: ReadTimeout
  name: The Bioinorganic Motif Database
  prefix: come
  url: https://www.flymine.org/come/entry?gn=MOL000160
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''compluyeast2dpage.dacya.ucm.es'', port=80):
    Max retries exceeded with url: /cgi-bin/2d/2d.cgi?ac=O08709 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f3c34f0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: O08709
  message: ConnectionError
  name: Compluyeast-2D-DB
  prefix: compulyeast
  url: http://compluyeast2dpage.dacya.ucm.es/cgi-bin/2d/2d.cgi?ac=O08709
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''crispr.i2bc.paris-saclay.fr'', port=443): Max
    retries exceeded with url: /cgi-bin/crispr/SpecieProperties_db.cgi?Taxon_id%255B%255D=551115
    (Caused by SSLError(SSLCertVerificationError(1, ''[SSL: CERTIFICATE_VERIFY_FAILED]
    certificate verify failed: certificate has expired (_ssl.c:1129)'')))'
  example: '551115'
  message: SSLError
  name: CRISPRdb
  prefix: crisprdb
  url: http://crispr.i2bc.paris-saclay.fr/cgi-bin/crispr/SpecieProperties_db.cgi?Taxon_id[]=551115
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''darcsite.genzentrum.lmu.de'', port=80): Max
    retries exceeded with url: /darc/view.php?id=1250 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f144f70>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '1250'
  message: ConnectionError
  name: Database of Aligned Ribosomal Complexes
  prefix: darc
  url: http://darcsite.genzentrum.lmu.de/darc/view.php?id=1250
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''dashr1.lisanwanglab.org'', port=443): Read
    timed out. (read timeout=15)'
  example: hsa-mir-200a
  message: ReadTimeout
  name: Database of small human noncoding RNAs
  prefix: dashr
  url: http://lisanwanglab.org/DASHR/entry/hsa-mir-200a
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''dashr1.lisanwanglab.org'', port=443): Read
    timed out. (read timeout=15)'
  example: hsa-mir-200a
  message: ReadTimeout
  name: DASHR expression
  prefix: dashr.expression
  url: https://dashr1.lisanwanglab.org/entry/hsa-mir-200a#hsa-mir-200a#exprPerTissueTable
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''webapps2.ucalgary.ca'', port=80): Read timed
    out. (read timeout=15)'
  example: Cu.me.I1
  message: ReadTimeout
  name: DBG2 Introns
  prefix: dbg2introns
  url: http://webapps2.ucalgary.ca/~groupii/cgi-bin/intron.cgi?name=Cu.me.I1
- contact_email: null
  contact_github: null
  contact_name: null
  context: '410'
  example: '1000000'
  message: HTTP 410
  name: NCBI Probe database Public registry of nucleic acid reagents
  prefix: dbprobe
  url: https://www.ncbi.nlm.nih.gov/probe/?term=1000000
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''dos-gdc.ucsc-cgp-dev.org'', port=443): Max
    retries exceeded with url: /ga4gh/dos/v1/dataobjects/23fa7b4b-9d68-429b-aece-658b11124bb3
    (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection object at
    0x11f0ffaf0>: Failed to establish a new connection: [Errno 8] nodename nor servname
    provided, or not known''))'
  example: 23fa7b4b-9d68-429b-aece-658b11124bb3#2017-03-24T18:43:16.886826-05:00
  message: ConnectionError
  name: Development Data Object Service
  prefix: dev.ga4ghdos
  url: https://dos-gdc.ucsc-cgp-dev.org/ga4gh/dos/v1/dataobjects/23fa7b4b-9d68-429b-aece-658b11124bb3#2017-03-24T18:43:16.886826-05:00
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: DDB0191090
  message: HTTP 500
  name: dictyBase
  prefix: dictybase
  url: http://dictybase.org/gene/DDB0191090
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''dip.doe-mbi.ucla.edu'', port=443): Max retries
    exceeded with url: /dip/DIPview.cgi?ID=DIP-743N (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: DIP-743N
  message: SSLError
  name: Database of Interacting Proteins
  prefix: dip
  url: https://dip.doe-mbi.ucla.edu/dip/DIPview.cgi?ID=DIP-743N
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''orion.rnet.missouri.edu'', port=80): Max retries
    exceeded with url: /~nz953/DOMMINO/index.php/result/show_network/2GC4 (Caused
    by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f13dac0>,
    ''Connection to orion.rnet.missouri.edu timed out. (connect timeout=15)''))'
  example: 2GC4
  message: ConnectTimeout
  name: Database of Macromolecular Interactions
  prefix: dommino
  url: http://orion.rnet.missouri.edu/~nz953/DOMMINO/index.php/result/show_network/2GC4
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '100'
  message: HTTP 404
  name: Description of Plant Viruses
  prefix: dpv
  url: http://www.dpvweb.net/dpv/showdpv.php?dpvno=100
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.flyrnai.org'', port=443): Max retries exceeded
    with url: /cgi-bin/RNAi_gene_lookup_public.pl?gname=DRSC05221 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: DRSC05221
  message: SSLError
  name: Drosophila RNAi Screening Center
  prefix: drsc
  url: http://www.flyrnai.org/cgi-bin/RNAi_gene_lookup_public.pl?gname=DRSC05221
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.ecogene.org'', port=80): Max retries exceeded
    with url: /gene/EG10173 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f1d6e80>, ''Connection to www.ecogene.org timed out. (connect timeout=15)''))'
  example: EG10173
  message: ConnectTimeout
  name: Database of Escherichia coli Sequence and Function
  prefix: ecogene
  url: http://www.ecogene.org/gene/EG10173
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''fungi.ensembl.org'', port=443): Read timed
    out. (read timeout=15)'
  example: CADAFLAT00006211
  message: ReadTimeout
  name: Ensembl Fungi, the Ensembl database for accessing genome-scale data from fungi.
  prefix: ensembl.fungi
  url: https://fungi.ensembl.org/id/CADAFLAT00006211
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''metazoa.ensembl.org'', port=443): Read timed
    out. (read timeout=15)'
  example: FBtr0084214
  message: ReadTimeout
  name: Ensembl Metazoa, the Ensembl database for accessing genome-scale data from
    non-vertebrate metazoa.
  prefix: ensembl.metazoa
  url: https://metazoa.ensembl.org/id/FBtr0084214
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''epd.epfl.ch'', port=443): Max retries exceeded
    with url: //cgi-bin/query_result.pl?out_format=NICE&Entry_0=TA_H3 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: TA_H3
  message: SSLError
  name: Eukaryotic Promoter Database
  prefix: epd
  url: http://epd.vital-it.ch/cgi-bin/query_result.pl?out_format=NICE&Entry_0=TA_H3
- contact_email: alpha.tom.kodamullil@scai.fraunhofer.de
  contact_github: akodamullil
  contact_name: Alpha Tom Kodamullil
  context: '404'
  example: '0000011'
  message: HTTP 404
  name: Epilepsy Ontology
  prefix: epio
  url: http://purl.obolibrary.org/obo/EPIO_0000011
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.clinicaltrialsregister.eu'', port=443):
    Max retries exceeded with url: /ctr-search/search?query=2008-005144-16 (Caused
    by SSLError(SSLCertVerificationError(1, ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate
    verify failed: unable to get local issuer certificate (_ssl.c:1129)'')))'
  example: 2008-005144-16
  message: SSLError
  name: EU Clinical Trials
  prefix: euclinicaltrials
  url: https://www.clinicaltrialsregister.eu/ctr-search/search?query=2008-005144-16
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: ENSG00000169174
  message: HTTP 404
  name: ExAC Gene
  prefix: exac.gene
  url: http://exac.broadinstitute.org/gene/ENSG00000169174
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: ENST00000407236
  message: HTTP 404
  name: ExAC Transcript
  prefix: exac.transcript
  url: http://exac.broadinstitute.org/transcript/ENST00000407236
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: 22-46615880-T-C
  message: HTTP 404
  name: ExAC Variant
  prefix: exac.variant
  url: http://exac.broadinstitute.org/variant/22-46615880-T-C
- contact_email: cp390@cam.ac.uk
  contact_github: Clare72
  contact_name: Clare Pilgrim
  context: '403'
  example: 00007294
  message: HTTP 403
  name: Drosophila gross anatomy
  prefix: fbbt
  url: https://flybase.org/cgi-bin/cvreport.pl?id=FBbt:00007294
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: 0187632
  message: HTTP 403
  name: FlyBase Reference Report
  prefix: fbrf
  url: https://flybase.org/reports/FBrf0187632
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: 0000190
  message: HTTP 403
  name: Flybase Cell Line
  prefix: fbtc
  url: https://flybase.org/reports/FBtc0000190
- contact_email: robert.hoehndorf@kaust.edu.sa
  contact_github: leechuck
  contact_name: Robert Hoehndorf
  context: 'HTTPConnectionPool(host=''aber-owl.net'', port=80): Read timed out. (read
    timeout=15)'
  example: '0005250'
  message: ReadTimeout
  name: Flora Phenotype Ontology
  prefix: flopo
  url: http://purl.obolibrary.org/obo/FLOPO_0005250
- contact_email: null
  contact_github: null
  contact_name: null
  context: '503'
  example: FR-FCM-ZYGW
  message: HTTP 503
  name: FlowRepository
  prefix: flowrepository
  url: https://flowrepository.org/id/FR-FCM-ZYGW
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: FBgn0011293
  message: HTTP 403
  name: FlyBase Gene
  prefix: flybase
  url: https://flybase.org/reports/FBgn0011293
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: familyName
  message: HTTP 404
  name: Friend of a Friend
  prefix: foaf
  url: http://xmlns.com/foaf/0.1/familyName
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: FOOD00020
  message: HTTP 500
  name: FooDB Food
  prefix: foodb.food
  url: https://foodb.ca/foods/FOOD00020
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''vocab.org'', port=443): Max retries exceeded
    with url: /frbr/core (Caused by SSLError(SSLCertVerificationError(1, ''[SSL: CERTIFICATE_VERIFY_FAILED]
    certificate verify failed: certificate has expired (_ssl.c:1129)'')))'
  example: Expression
  message: SSLError
  name: Functional Requirements for Bibliographic Records
  prefix: frbr
  url: http://purl.org/vocab/frbr/core#Expression
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''compbio.cs.queensu.ca'', port=80): Max retries
    exceeded with url: /cgi-bin/compbio/search/main.cgi?search_mode=id&amp;id_type=snp_id&amp;id_val=rs17852708
    (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f14ad30>,
    ''Connection to compbio.cs.queensu.ca timed out. (connect timeout=15)''))'
  example: rs17852708
  message: ConnectTimeout
  name: F-SNP
  prefix: fsnp
  url: http://compbio.cs.queensu.ca/cgi-bin/compbio/search/main.cgi?search_mode=id&amp;id_type=snp_id&amp;id_val=rs17852708
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''func.mshri.on.ca'', port=80): Max retries exceeded
    with url: /fly/genes/list_functional_scores/10194 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f14aa30>: Failed to establish a new connection: [Errno 51] Network
    is unreachable''))'
  example: '10194'
  message: ConnectionError
  name: FuncBase Fly
  prefix: funcbase.fly
  url: http://func.mshri.on.ca/fly/genes/list_functional_scores/10194
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''func.mshri.on.ca'', port=80): Max retries exceeded
    with url: /human/genes/list_functional_scores/119514 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f0ed0d0>: Failed to establish a new connection: [Errno 51] Network
    is unreachable''))'
  example: '119514'
  message: ConnectionError
  name: FuncBase Human
  prefix: funcbase.human
  url: http://func.mshri.on.ca/human/genes/list_functional_scores/119514
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''func.mshri.on.ca'', port=80): Max retries exceeded
    with url: /mouse/genes/list_functional_scores/1351341 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f0eddc0>: Failed to establish a new connection: [Errno 51] Network
    is unreachable''))'
  example: '1351341'
  message: ConnectionError
  name: FuncBase Mouse
  prefix: funcbase.mouse
  url: http://func.mshri.on.ca/mouse/genes/list_functional_scores/1351341
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''func.mshri.on.ca'', port=80): Max retries exceeded
    with url: /yeast/genes/list_functional_scores/2701 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f155370>: Failed to establish a new connection: [Errno 51] Network
    is unreachable''))'
  example: '2701'
  message: ConnectionError
  name: FuncBase Yeast
  prefix: funcbase.yeast
  url: http://func.mshri.on.ca/yeast/genes/list_functional_scores/2701
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '2679240'
  message: HTTP 404
  name: Network of Different Plant Genomic Research Projects
  prefix: gabi
  url: http://www.gabipd.org/database/cgi-bin/GreenCards.pl.cgi?BioObjectId=2679240&Mode=ShowBioObject
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: ABL1
  message: HTTP 403
  name: GeneCards
  prefix: genecards
  url: https://www.genecards.org/cgi-bin/carddisp.pl?gene=ABL1
- contact_email: null
  contact_github: null
  contact_name: null
  context: '503'
  example: '4892'
  message: HTTP 503
  name: GeneFarm
  prefix: genefarm
  url: https://urgi.versailles.inra.fr/Genefarm/Gene/display_gene.htpl?GENE_ID=4892
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: ACM1_HUMAN
  message: HTTP 404
  name: GLIDA GPCR
  prefix: glida.gpcr
  url: http://pharminfo.pharm.kyoto-u.ac.jp/services/glida/gpcr_information.php?id=ACM1_HUMAN
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: L000001
  message: HTTP 404
  name: GLIDA Ligand
  prefix: glida.ligand
  url: http://pharminfo.pharm.kyoto-u.ac.jp/services/glida/ligand_information.php?id=L000001
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''gmd.mpimp-golm.mpg.de'', port=80): Read timed
    out. (read timeout=15)'
  example: 68513255-fc44-4041-bc4b-4fd2fae7541d
  message: ReadTimeout
  name: Golm Metabolome Database
  prefix: gmd
  url: http://gmd.mpimp-golm.mpg.de/Metabolites/68513255-fc44-4041-bc4b-4fd2fae7541d.aspx
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''wheat.pw.usda.gov'', port=443): Max retries
    exceeded with url: /cgi-bin/GG3/report.cgi?class=reference&name=WGS-95-1333 (Caused
    by SSLError(SSLCertVerificationError(1, ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate
    verify failed: unable to get local issuer certificate (_ssl.c:1129)'')))'
  example: WGS-95-1333
  message: SSLError
  name: GrainGenes
  prefix: graingenes.reference
  url: https://wheat.pw.usda.gov/cgi-bin/GG3/report.cgi?class=reference&name=WGS-95-1333
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''wheat.pw.usda.gov'', port=80): Max retries exceeded
    with url: /report?class=gene;name=1-FEH+w3 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f0f7040>: Failed to establish a new connection: [Errno 61] Connection
    refused''))'
  example: 1-FEH+w3
  message: ConnectionError
  name: GrainGenes
  prefix: graingenes.symbol
  url: http://wheat.pw.usda.gov/report?class=gene;name=1-FEH+w3
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '100000'
  message: HTTP 404
  name: 16S rRNA gene database
  prefix: greengenes
  url: http://greengenes.lbl.gov/cgi-bin/show_one_record_v2.pl?prokMSA_id=100000
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.ars-grin.gov'', port=443): Max retries
    exceeded with url: /cgi-bin/npgs/html/taxon.pl?19333 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: '19333'
  message: SSLError
  name: Germplasm Resources Information Network
  prefix: grin.taxonomy
  url: http://www.ars-grin.gov/cgi-bin/npgs/html/taxon.pl?19333
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: '10142'
  message: HTTP 500
  name: G-Rich Sequences Database
  prefix: grsdb
  url: http://bioinformatics.ramapo.edu/GRSDB2/geneview.php?geneID=10142
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: HGVM15354
  message: HTTP 403
  name: GWAS Central Marker
  prefix: gwascentral.marker
  url: https://www.gwascentral.org/marker/HGVM15354
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''euhcvdb.ibcp.fr'', port=443): Max retries exceeded
    with url: /euHCVdb/do/displayHCVEntry?primaryAC=M58335 (Caused by SSLError(CertificateError("hostname
    ''euhcvdb.ibcp.fr'' doesn''t match either of ''npsa-prabi.ibcp.fr'', ''npsa-pbil.ibcp.fr''")))'
  example: M58335
  message: SSLError
  name: Hepatitis C Virus Database
  prefix: hcvdb
  url: https://euhcvdb.ibcp.fr/euHCVdb/do/displayHCVEntry?primaryAC=M58335
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '63'
  message: HTTP 404
  name: Homeodomain Research
  prefix: hdr
  url: http://research.nhgri.nih.gov/apps/homeodomain/web/index.cgi?mode=view&amp;view=proteins&amp;id=63
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''pbil.univ-lyon1.fr'', port=80): Max retries
    exceeded with url: /cgi-bin/view-tree.pl?db=HOGENOM5&query=HBG284870 (Caused by
    ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f20cac0>,
    ''Connection to pbil.univ-lyon1.fr timed out. (connect timeout=15)''))'
  example: HBG284870
  message: ConnectTimeout
  name: Database of Complete Genome Homologous Genes Families
  prefix: hogenom
  url: http://pbil.univ-lyon1.fr/cgi-bin/view-tree.pl?db=HOGENOM5&query=HBG284870
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: SEQF1003
  message: HTTP 404
  name: HOMD Sequence Metainformation
  prefix: homd.seq
  url: http://www.homd.org/modules.php?op=modload&name=GenomeList&file=index&link=detailinfo&seqid=SEQF1003
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'Invalid URL ''www.homd.org/modules.php?op=modload&name=HOMD&view=dynamic&oraltaxonid=811'':
    No scheme supplied. Perhaps you meant http://www.homd.org/modules.php?op=modload&name=HOMD&view=dynamic&oraltaxonid=811?'
  example: '811'
  message: MissingSchema
  name: HOMD Taxonomy
  prefix: homd.taxon
  url: www.homd.org/modules.php?op=modload&name=HOMD&view=dynamic&oraltaxonid=811
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''pbil.univ-lyon1.fr'', port=80): Max retries
    exceeded with url: /cgi-bin/view-tree.pl?query=HBG004341&db=HOVERGEN (Caused by
    ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f21d100>,
    ''Connection to pbil.univ-lyon1.fr timed out. (connect timeout=15)''))'
  example: HBG004341
  message: ConnectTimeout
  name: Homologous Vertebrate Genes Database
  prefix: hovergen
  url: http://pbil.univ-lyon1.fr/cgi-bin/view-tree.pl?query=HBG004341&db=HOVERGEN
- contact_email: dr.sebastian.koehler@gmail.com
  contact_github: drseb
  contact_name: Sebastian Koehler
  context: 'HTTPSConnectionPool(host=''hpo.jax.org'', port=443): Max retries exceeded
    with url: /app/browse/term/HP:0011140 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: '0011140'
  message: SSLError
  name: Human Phenotype Ontology
  prefix: hp
  url: https://hpo.jax.org/app/browse/term/HP:0011140
- contact_email: null
  contact_github: null
  contact_name: null
  context: No connection adapters were found for 'ftp://ftp.embl-heidelberg.de/pub/databases/protein_extras/hssp/102l.hssp.bz2'
  example: 102l
  message: InvalidSchema
  name: Database of homology-derived secondary structure of proteins
  prefix: hssp
  url: ftp://ftp.embl-heidelberg.de/pub/databases/protein_extras/hssp/102l.hssp.bz2
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '100'
  message: HTTP 404
  name: ICEberg element
  prefix: iceberg.element
  url: http://db-mml.sjtu.edu.cn/ICEberg/feature_page.php?ice_id=100
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '1'
  message: HTTP 404
  name: ICEberg family
  prefix: iceberg.family
  url: http://db-mml.sjtu.edu.cn/ICEberg/browse_result.php?type=fam&fam_id=1
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''registry.api.hq.identifiers.org'', port=80):
    Max retries exceeded with url: /semanticApi/getRegistryOntology (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f1ba220>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: DataCollection
  message: ConnectionError
  name: Identifiers.org Ontology
  prefix: idoo
  url: http://registry.api.hq.identifiers.org/semanticApi/getRegistryOntology#DataCollection
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''biomodels.net'', port=443): Max retries exceeded
    with url: /vocab/idot.rdf (Caused by SSLError(CertificateError("hostname ''biomodels.net''
    doesn''t match either of ''www4.ebi.ac.uk'', ''www.www4.ebi.ac.uk''")))'
  example: identifierPattern
  message: SSLError
  name: Identifiers.org Terms
  prefix: idot
  url: https://biomodels.net/vocab/idot.rdf#identifierPattern
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: A*01:01:01:01
  message: HTTP 404
  name: IMGT/HLA human major histocompatibility complex sequence database
  prefix: imgt.hla
  url: https://www.ebi.ac.uk/cgi-bin/imgt/hla/get_allele.cgi?A*01:01:01:01
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: fluticasone
  message: HTTP 404
  name: International Nonproprietary Names
  prefix: inn
  url: https://mednet-communities.net/inn/db/ViewINN.aspx?i=fluticasone
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: CY077097
  message: HTTP 404
  name: IRD Segment Sequence
  prefix: ird.segment
  url: http://www.fludb.org/brc/fluSegmentDetails.do?ncbiGenomicAccession=CY077097
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''wodaklab.org'', port=443): Max retries exceeded
    with url: /iRefWeb/interaction/show/617102 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has
    expired (_ssl.c:1129)'')))'
  example: '617102'
  message: SSLError
  name: iRefWeb
  prefix: irefweb
  url: http://wodaklab.org/iRefWeb/interaction/show/617102
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www-is.biotoul.fr'', port=443): Max retries
    exceeded with url: /scripts/ficheIS.php?name=ISA1083-2 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: ISA1083-2
  message: SSLError
  name: Insertion sequence elements database
  prefix: isfinder
  url: https://www-is.biotoul.fr/scripts/ficheIS.php?name=ISA1083-2
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.itis.gov'', port=443): Read timed out.
    (read timeout=15)'
  example: '589462'
  message: ReadTimeout
  name: Integrated Taxonomic Information System
  prefix: itis
  url: https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=589462
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: ITO_01625
  message: HTTP 404
  name: Intelligence Task Ontology
  prefix: ito
  url: https://bioportal.bioontology.org/ontologies/ITO/?p=classes&conceptid=https%3A%2F%2Fai-strategies.org%2Fontology%2FITO_01625
- contact_email: null
  contact_github: null
  contact_name: null
  context: '400'
  example: '005012'
  message: HTTP 400
  name: JAX Mice
  prefix: jaxmice
  url: http://jaxmice.jax.org/strain/005012.html
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: JCGG-STR008690
  message: HTTP 404
  name: Japan Consortium for Glycobiology and Glycotechnology Database
  prefix: jcggdb
  url: http://jcggdb.jp/idb/jcggdb/JCGG-STR008690
- contact_email: null
  contact_github: null
  contact_name: null
  context: '420'
  example: '3075966'
  message: HTTP 420
  name: Digital archive of scholarly articles
  prefix: jstor
  url: http://www.jstor.org/stable/3075966
- contact_email: null
  contact_github: null
  contact_name: null
  context: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
  example: '10020.2'
  message: ConnectionError
  name: Korean Cell Line Bank
  prefix: kclb
  url: https://cellbank.snu.ac.kr/english/sub/catalog.php?s_cellid=464&page=detail_info&CatNo=59&strQ=10020.2
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: BBA0001
  message: HTTP 404
  name: LipidBank
  prefix: lipidbank
  url: http://lipidbank.jp/cgi-bin/detail.cgi?id=BBA0001
- contact_email: null
  contact_github: null
  contact_name: null
  context: No connection adapters were found for 'ftp://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_1.xml'
  example: LRG_1
  message: InvalidSchema
  name: Locus Reference Genomic
  prefix: lrg
  url: ftp://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_1.xml
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''matrixdb.univ-lyon1.fr'', port=80): Max retries
    exceeded with url: /cgi-bin/current/newPort?type=biomolecule&value=MULT_4_VAR1_bovine
    (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f23d9a0>,
    ''Connection to matrixdb.univ-lyon1.fr timed out. (connect timeout=15)''))'
  example: MULT_4_VAR1_bovine
  message: ConnectTimeout
  name: MatrixDB
  prefix: matrixdb
  url: http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=MULT_4_VAR1_bovine
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''matrixdb.univ-lyon1.fr'', port=80): Max retries
    exceeded with url: //cgi-bin/current/newPort?type=association&value=P00747__P07355&class=Association
    (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f0ed130>,
    ''Connection to matrixdb.univ-lyon1.fr timed out. (connect timeout=15)''))'
  example: P00747__P07355
  message: ConnectTimeout
  name: MatrixDB Association
  prefix: matrixdb.association
  url: http://matrixdb.univ-lyon1.fr//cgi-bin/current/newPort?type=association&value=P00747__P07355&class=Association
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: '17186'
  message: HTTP 500
  name: MeSH 2012
  prefix: mesh.2012
  url: http://www.nlm.nih.gov/cgi/mesh/2012/MB_cgi?mode=&index=17186&view=expanded
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: '17165'
  message: HTTP 500
  name: MeSH 2013
  prefix: mesh.2013
  url: http://www.nlm.nih.gov/cgi/mesh/2013/MB_cgi?mode=&index=17165&view=expanded
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.metabolome-express.org'', port=443): Max
    retries exceeded with url: /datasetview.php?datasetid=36 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f3c3c70>: Failed to establish a new connection: [Errno 61] Connection
    refused''))'
  example: '36'
  message: ConnectionError
  name: Metabolome Express
  prefix: mex
  url: https://www.metabolome-express.org/datasetview.php?datasetid=36
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''aclame.ulb.ac.be'', port=80): Max retries exceeded
    with url: /perl/Aclame/Genomes/mge_view.cgi?view=info&id=mge:2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f24e430>, ''Connection to aclame.ulb.ac.be timed out. (connect timeout=15)''))'
  example: '2'
  message: ConnectTimeout
  name: Aclame
  prefix: mge
  url: http://aclame.ulb.ac.be/perl/Aclame/Genomes/mge_view.cgi?view=info&id=mge:2
- contact_email: carrine.blank@umontana.edu
  contact_github: carrineblank
  contact_name: Carrine Blank
  context: '404'
  example: 0002999
  message: HTTP 404
  name: Ontology of Prokaryotic Phenotypic and Metabolic Characters
  prefix: micro
  url: http://purl.obolibrary.org/obo/MICRO_0002999
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.merckmillipore.com'', port=443): Read timed
    out. (read timeout=15)'
  example: SCC111
  message: ReadTimeout
  name: Merck Millipore (EMD Millipore)
  prefix: millipore
  url: https://www.merckmillipore.com/catalogue/item/SCC111
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MINT-10000
  message: HTTP 404
  name: Molecular Interaction Database
  prefix: mint
  url: http://mint.bio.uniroma2.it/mint/search/inFrameInteraction.do?interactionAc=MINT-10000
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''mirtarbase.mbc.nctu.edu.tw'', port=80): Max
    retries exceeded with url: /php/detail.php?mirtid=MIRT000002 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f269d60>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: MIRT000002
  message: ConnectionError
  name: miRTarBase
  prefix: mirtarbase
  url: http://mirtarbase.mbc.nctu.edu.tw/php/detail.php?mirtid=MIRT000002
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '37'
  message: HTTP 404
  name: Melanoma Molecular Map Project Biomaps
  prefix: mmmp.biomaps
  url: http://www.mmmp.org/MMMP/public/biomap/viewBiomap.mmmp?id=37
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MMP743597.11
  message: HTTP 404
  name: MarCat
  prefix: mmp.cat
  url: https://mmp.sfb.uit.no/databases/marcat/#/records/MMP743597.11
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: 128796-39-4
  message: HTTP 403
  name: Molbase
  prefix: molbase
  url: http://www.molbase.com/en/index.php?app=search&search_keyword=128796-39-4
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''molmedb.upol.cz'', port=443): Max retries exceeded
    with url: /mol/MM00040 (Caused by SSLError(SSLCertVerificationError(1, ''[SSL:
    CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer
    certificate (_ssl.c:1129)'')))'
  example: MM00040
  message: SSLError
  name: MolMeDB
  prefix: molmedb
  url: https://molmedb.upol.cz/mol/MM00040
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '172'
  message: HTTP 404
  name: Microbial Protein Interaction Database
  prefix: mpid
  url: http://www.jcvi.org/mpidb/experiment.php?interaction_id=172
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MCDS_S_0000000001
  message: HTTP 404
  name: MultiCellDS
  prefix: multicellds
  url: http://multicellds.org/MultiCellDB/MCDS_S_0000000001
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MCDS_L_0000000001
  message: HTTP 404
  name: MultiCellDS Digital Cell Line
  prefix: multicellds.cell_line
  url: http://multicellds.org/MultiCellDB/MCDS_L_0000000001
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MCDS_C_0000000001
  message: HTTP 404
  name: MultiCellDS collection
  prefix: multicellds.collection
  url: http://multicellds.org/MultiCellDB/MCDS_C_0000000001
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MCDS_S_0000000001
  message: HTTP 404
  name: MultiCellDS Digital snapshot
  prefix: multicellds.snapshot
  url: http://multicellds.org/MultiCellDB/MCDS_S_0000000001
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: ML0224
  message: HTTP 404
  name: MycoBrowser leprae
  prefix: myco.lepra
  url: http://mycobrowser.epfl.ch/leprosysearch.php?gene+name=ML0224
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MMAR_2462
  message: HTTP 404
  name: MycoBrowser marinum
  prefix: myco.marinum
  url: http://mycobrowser.epfl.ch/marinosearch.php?gene+name=MMAR_2462
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: MSMEG_3769
  message: HTTP 404
  name: MycoBrowser smegmatis
  prefix: myco.smeg
  url: http://mycobrowser.epfl.ch/smegmasearch.php?gene+name=MSMEG_3769
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: Rv1908c
  message: HTTP 404
  name: TubercuList knowledge base
  prefix: myco.tuber
  url: http://tuberculist.epfl.ch/quicksearch.php?gene+name=Rv1908c
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '349124'
  message: HTTP 403
  name: Fungal Nomenclature and Species Bank
  prefix: mycobank
  url: http://www.mycobank.org/Biolomics.aspx?Table=Mycobank&MycoBankNr_=349124
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '28'
  message: HTTP 404
  name: Natural Product-Drug Interaction Research Data Repository
  prefix: napdi
  url: https://repo.napdi.org/study/28
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''neuromorpho.org'', port=443): Max retries exceeded
    with url: /neuron_info.jsp?neuron_name=Rosa2 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
    issuer certificate (_ssl.c:1129)'')))'
  example: Rosa2
  message: SSLError
  name: NeuroMorpho
  prefix: neuromorpho
  url: http://neuromorpho.org/neuron_info.jsp?neuron_name=Rosa2
- contact_email: tgbugs@gmail.com
  contact_github: tgbugs
  contact_name: Tom Gillespie
  context: '404'
  example: '91005'
  message: HTTP 404
  name: 'NIF Standard Ontology: Cell Types'
  prefix: nlx.cell
  url: http://uri.neuinfo.org/nif/nifstd/nlx_cell_91005
- contact_email: tgbugs@gmail.com
  contact_github: tgbugs
  contact_name: Tom Gillespie
  context: '404'
  example: '90801'
  message: HTTP 404
  name: 'NIF Standard Ontology: Chemical'
  prefix: nlx.chem
  url: http://uri.neuinfo.org/nif/nifstd/nlx_chem_90801
- contact_email: tgbugs@gmail.com
  contact_github: tgbugs
  contact_name: Tom Gillespie
  context: '404'
  example: '20090303'
  message: HTTP 404
  name: NeuroLex Dysfunction
  prefix: nlx.dys
  url: http://uri.neuinfo.org/nif/nifstd/nlx_dys_20090303
- contact_email: tgbugs@gmail.com
  contact_github: tgbugs
  contact_name: Tom Gillespie
  context: '404'
  example: '90801'
  message: HTTP 404
  name: 'NIF Standard Ontology: Cognitive Function'
  prefix: nlx.func
  url: http://uri.neuinfo.org/nif/nifstd/nlx_func_90801
- contact_email: tgbugs@gmail.com
  contact_github: tgbugs
  contact_name: Tom Gillespie
  context: '404'
  example: '90901'
  message: HTTP 404
  name: 'NIF Standard Ontology: Investigations'
  prefix: nlx.inv
  url: http://uri.neuinfo.org/nif/nifstd/nlx_inv_90901
- contact_email: tgbugs@gmail.com
  contact_github: tgbugs
  contact_name: Tom Gillespie
  context: '404'
  example: '90806'
  message: HTTP 404
  name: 'NIF Standard Ontology: Molecules'
  prefix: nlx.mol
  url: http://uri.neuinfo.org/nif/nifstd/nlx_mol_90806
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '377550'
  message: HTTP 404
  name: NONCODE v3
  prefix: noncodev3
  url: http://www.noncode.org/NONCODERv3/ncrna.php?ncid=377550
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''en.bioinfo.org'', port=443): Max retries exceeded
    with url: /NONCODEv4/show_gene.php?id=NONHSAG00001 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f1d6850>: Failed to establish a new connection: [Errno 61] Connection
    refused''))'
  example: NONHSAG00001
  message: ConnectionError
  name: NONCODE v4 Gene
  prefix: noncodev4.gene
  url: http://www.bioinfo.org/NONCODEv4/show_gene.php?id=NONHSAG00001
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''en.bioinfo.org'', port=443): Max retries exceeded
    with url: /NONCODEv4/show_rna.php?id=NONHSAT000001 (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
    object at 0x11f136d60>: Failed to establish a new connection: [Errno 61] Connection
    refused''))'
  example: NONHSAT000001
  message: ConnectionError
  name: NONCODE v4 Transcript
  prefix: noncodev4.rna
  url: http://www.bioinfo.org/NONCODEv4/show_rna.php?id=NONHSAT000001
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.novusbio.com'', port=443): Read timed out.
    (read timeout=15)'
  example: nb100-56351
  message: ReadTimeout
  name: Novus Biologicals
  prefix: novus
  url: https://www.novusbio.com/products/nb100-56351
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: 1-18
  message: HTTP 500
  name: Open Citation Identifier
  prefix: oci
  url: https://w3id.org/oc/oci/1-18
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.oid-info.com'', port=80): Max retries exceeded
    with url: /cgi-bin/display?oid=2.16.840&submit=Display&action=display (Caused
    by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f3f2ca0>,
    ''Connection to www.oid-info.com timed out. (connect timeout=15)''))'
  example: 2.16.840
  message: ConnectTimeout
  name: OID Repository
  prefix: oid
  url: http://www.oid-info.com/cgi-bin/display?oid=2.16.840&submit=Display&action=display
- contact_email: hajo.rijgersberg@wur.nl
  contact_github: null
  contact_name: null
  context: '404'
  example: Dimension
  message: HTTP 404
  name: Ontology of units of Measure
  prefix: om
  url: http://www.ontology-of-units-of-measure.org/resource/om-2/Dimension
- contact_email: ahamosh@jhmi.edu
  contact_github: ahamosh
  contact_name: Ada Hamosh
  context: '403'
  example: '603903'
  message: HTTP 403
  name: Online Mendelian Inheritance in Man
  prefix: omim
  url: https://omim.org/entry/603903
- contact_email: ahamosh@jhmi.edu
  contact_github: ahamosh
  contact_name: Ada Hamosh
  context: '403'
  example: PS214100
  message: HTTP 403
  name: OMIM Phenotypic Series
  prefix: omim.ps
  url: https://omim.org/phenotypicSeries/PS214100
- contact_email: huang@southalabama.edu
  contact_github: Huang-OMIT
  contact_name: Jingshan Huang
  context: '404'
  example: 0000069
  message: HTTP 404
  name: Ontology for MicroRNA Target
  prefix: omit
  url: https://www.ebi.ac.uk/ols/ontologies/omit/terms?short_form=OMIT_0000069
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '00573'
  message: HTTP 404
  name: Ontology of Physics for Biology
  prefix: opb
  url: http://purl.bioontology.org/ontology/OPB?conceptid=http%3A%2F%2Fbhi.washington.edu%2FOPB%23OPB_00573
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: AADB12
  message: HTTP 403
  name: Oryza Tag Line
  prefix: otl
  url: http://oryzatagline.cirad.fr/cgi-bin/general_mutant.pl?line=AADB12
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '70'
  message: HTTP 404
  name: P3DB Protein
  prefix: p3db.protein
  url: http://www.p3db.org/protein.php?id=70&amp;ref=0
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '65'
  message: HTTP 404
  name: P3DB Site
  prefix: p3db.site
  url: http://www.p3db.org/phosphosite.php?id=65&ref=0
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''fossilworks.org'', port=80): Max retries exceeded
    with url: /?a=taxonInfo&taxon_no=83088 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f0ddaf0>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '83088'
  message: ConnectionError
  name: Paleobiology Database
  prefix: paleodb
  url: http://fossilworks.org/?a=taxonInfo&taxon_no=83088
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.pantree.org'', port=80): Read timed out.'
  example: PTN000000026
  message: ConnectionError
  name: PANTHER Node
  prefix: panther.node
  url: http://www.pantree.org/node/annotationNode.jsp?id=PTN000000026
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.pathwaycommons.org'', port=80): Read timed
    out. (read timeout=15)'
  example: '485991'
  message: ReadTimeout
  name: Pathway Commons
  prefix: pathwaycommons
  url: http://www.pathwaycommons.org/pc/record2.do?id=485991
- contact_email: null
  contact_github: null
  contact_name: null
  context: No host specified.
  example: authoredBy
  message: InvalidURL
  name: Provenance, Authoring, and Versioning Vocabulary
  prefix: pav
  url: http://purl.org/pav/authoredBy
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.pazar.info'', port=80): Max retries exceeded
    with url: /cgi-bin/tf_search.cgi?geneID=TF0001053 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f227a90>, ''Connection to www.pazar.info timed out. (connect timeout=15)''))'
  example: TF0001053
  message: ConnectTimeout
  name: Pazar Transcription Factor
  prefix: pazar
  url: http://www.pazar.info/cgi-bin/tf_search.cgi?geneID=TF0001053
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: TRQ
  message: HTTP 404
  name: Protein Data Bank Ligand
  prefix: pdb.ligand
  url: http://www.rcsb.org/pdb/ligand/ligandsummary.do?hetId=TRQ
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: derivatives%2Fthiocyclam%20hydrochloride
  message: HTTP 404
  name: Alan Wood's Pesticides
  prefix: pesticides
  url: http://www.alanwood.net/pesticides/derivatives%2Fthiocyclam%20hydrochloride.html
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''kinase.bioinformatics.tw'', port=80): Max retries
    exceeded with url: /showall.jsp?type=Kinase&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=1
    (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x11f3b25b0>:
    Failed to establish a new connection: [Errno 8] nodename nor servname provided,
    or not known''))'
  example: AURKA
  message: ConnectionError
  name: PhosphoPoint Kinase
  prefix: phosphopoint.kinase
  url: http://kinase.bioinformatics.tw/showall.jsp?type=Kinase&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=1
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''kinase.bioinformatics.tw'', port=80): Max retries
    exceeded with url: /showall.jsp?type=PhosphoProtein&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=0
    (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x11f3b21f0>:
    Failed to establish a new connection: [Errno 8] nodename nor servname provided,
    or not known''))'
  example: AURKA
  message: ConnectionError
  name: PhosphoPoint Phosphoprotein
  prefix: phosphopoint.protein
  url: http://kinase.bioinformatics.tw/showall.jsp?type=PhosphoProtein&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=0
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '12300'
  message: HTTP 403
  name: PhosphoSite Protein
  prefix: phosphosite.protein
  url: http://www.phosphosite.org/proteinAction.do?id=12300
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '2842'
  message: HTTP 403
  name: PhosphoSite Residue
  prefix: phosphosite.residue
  url: http://www.phosphosite.org/siteAction.do?id=2842
- contact_email: null
  contact_github: null
  contact_name: null
  context: '503'
  example: Glyma0021s00410
  message: HTTP 503
  name: Plant Genome Network
  prefix: phytozome.locus
  url: http://www.phytozome.net/genePage.php?crown&method=0&search=1&detail=1&searchText=locusname:Glyma0021s00410
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''pid.nci.nih.gov'', port=80): Max retries exceeded
    with url: /search/pathway_landing.shtml?what=graphic&jpg=on&pathway_id=eff796f3-6195-11e5-8ac5-06603eb7f303
    (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x11f1dc760>:
    Failed to establish a new connection: [Errno 8] nodename nor servname provided,
    or not known''))'
  example: eff796f3-6195-11e5-8ac5-06603eb7f303
  message: ConnectionError
  name: 'NCI Pathway Interaction Database: Pathway'
  prefix: pid.pathway
  url: http://pid.nci.nih.gov/search/pathway_landing.shtml?what=graphic&jpg=on&pathway_id=eff796f3-6195-11e5-8ac5-06603eb7f303
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''cbg.garvan.unsw.edu.au'', port=80): Max retries
    exceeded with url: /pina/interactome.oneP.do?showExtend=null&ac=Q13485 (Caused
    by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f144370>,
    ''Connection to cbg.garvan.unsw.edu.au timed out. (connect timeout=15)''))'
  example: Q13485
  message: ConnectTimeout
  name: Protein Interaction Network Analysis
  prefix: pina
  url: http://cbg.garvan.unsw.edu.au/pina/interactome.oneP.do?showExtend=null&ac=Q13485
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''pir.georgetown.edu'', port=443): Max retries
    exceeded with url: /cgi-bin/ipcSF?id=PIRSF000100 (Caused by SSLError(CertificateError("hostname
    ''pir.georgetown.edu'' doesn''t match either of ''lod.proconsortium.org'', ''tncentral.proteininformationresource.org'',
    ''sparql.proconsortium.org'', ''ftp.proteininformationresource.org'', ''proconsortium.org'',
    ''proteininformationresource.org'', ''www.proteininformationresource.org''")))'
  example: PIRSF000100
  message: SSLError
  name: PIR Superfamily Classification System
  prefix: pirsf
  url: https://pir.georgetown.edu/cgi-bin/ipcSF?id=PIRSF000100
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''planttfdb.cbi.pku.edu.cn'', port=80): Max retries
    exceeded with url: /tf.php?uid=Ath_AT1G01030.1 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f275340>: Failed to establish a new connection: [Errno 61] Connection
    refused''))'
  example: Ath_AT1G01030.1
  message: ConnectionError
  name: Plant Transcription Factor Database
  prefix: planttfdb
  url: http://planttfdb.cbi.pku.edu.cn/tf.php?uid=Ath_AT1G01030.1
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''cutdb.burnham.org'', port=80): Max retries exceeded
    with url: /relation/show/25782 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f2b0430>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '25782'
  message: ConnectionError
  name: CutDB
  prefix: pmap.cutdb
  url: http://cutdb.burnham.org/relation/show/25782
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''substrate.burnham.org'', port=80): Max retries
    exceeded with url: /protein/annotation/1915/html (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f3ff910>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: '1915'
  message: ConnectionError
  name: SubstrateDB
  prefix: pmap.substratedb
  url: http://substrate.burnham.org/protein/annotation/1915/html
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''bioinformatics.cineca.it'', port=443): Max
    retries exceeded with url: /PMDB/user//search.php?idsearch=PM0012345 (Caused by
    ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11f25faf0>,
    ''Connection to bioinformatics.cineca.it timed out. (connect timeout=15)''))'
  example: PM0012345
  message: ConnectTimeout
  name: Protein Model Database
  prefix: pmdb
  url: https://bioinformatics.cineca.it/PMDB/user//search.php?idsearch=PM0012345
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.pocketome.org'', port=80): Max retries exceeded
    with url: /files/1433C_TOBAC_1_252.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f227220>, ''Connection to www.pocketome.org timed out. (connect
    timeout=15)''))'
  example: 1433C_TOBAC_1_252
  message: ConnectTimeout
  name: Pocketome
  prefix: pocketome
  url: http://www.pocketome.org/files/1433C_TOBAC_1_252.html
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''prodom.prabi.fr'', port=80): Max retries exceeded
    with url: /prodom/current/cgi-bin/request.pl?question=DBEN&query=PD10000 (Caused
    by NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x11f2dbcd0>:
    Failed to establish a new connection: [Errno 8] nodename nor servname provided,
    or not known''))'
  example: PD10000
  message: ConnectionError
  name: ProDom
  prefix: prodom
  url: http://prodom.prabi.fr/prodom/current/cgi-bin/request.pl?question=DBEN&query=PD10000
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: AC119
  message: HTTP 404
  name: ProGlycProt
  prefix: proglyc
  url: http://www.proglycprot.org/detail.aspx?ProId=AC119
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.protonet.cs.huji.ac.il'', port=80): Max
    retries exceeded with url: /requested/cluster_card.php?cluster=4349895 (Caused
    by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f126e80>,
    ''Connection to www.protonet.cs.huji.ac.il timed out. (connect timeout=15)''))'
  example: '4349895'
  message: ConnectTimeout
  name: ProtoNet Cluster
  prefix: protonet.cluster
  url: http://www.protonet.cs.huji.ac.il/requested/cluster_card.php?cluster=4349895
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.protonet.cs.huji.ac.il'', port=80): Max
    retries exceeded with url: /requested/protein_card.php?protein_id=16941567 (Caused
    by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f3c39a0>,
    ''Connection to www.protonet.cs.huji.ac.il timed out. (connect timeout=15)''))'
  example: '16941567'
  message: ConnectTimeout
  name: ProtoNet ProteinCard
  prefix: protonet.proteincard
  url: http://www.protonet.cs.huji.ac.il/requested/protein_card.php?protein_id=16941567
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.rebuildingakidney.org'', port=443): Read
    timed out. (read timeout=15)'
  example: Q-2958
  message: ReadTimeout
  name: Rebuilding a Kidney
  prefix: rbk
  url: https://www.rebuildingakidney.org/id/Q-2958
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '101'
  message: HTTP 403
  name: REBASE restriction enzyme database
  prefix: rebase
  url: http://rebase.neb.com/rebase/enz/101.html
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.receptome.org'', port=80): Max retries exceeded
    with url: /families/Frameset_family.asp?ProtType=Receptor&FamId=5.1 (Caused by
    NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x11f2a06a0>:
    Failed to establish a new connection: [Errno 8] nodename nor servname provided,
    or not known''))'
  example: '5.1'
  message: ConnectionError
  name: Human Plasma Membrane Receptome Families
  prefix: receptome.family
  url: http://www.receptome.org/families/Frameset_family.asp?ProtType=Receptor&FamId=5.1
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '051'
  message: HTTP 404
  name: The RNA Modification Database
  prefix: rnamod
  url: http://rna.rega.kuleuven.be/cgi-bin/rnamods/rnashow.pl?051
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''mods.rna.albany.edu'', port=443): Max retries
    exceeded with url: /mods/modifications/view/101 (Caused by SSLError(SSLCertVerificationError(1,
    ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate
    (_ssl.c:1129)'')))'
  example: '101'
  message: SSLError
  name: RNA Modification Database
  prefix: rnamods
  url: http://mods.rna.albany.edu/mods/modifications/view/101
- contact_email: cjmungall@lbl.gov
  contact_github: cmungall
  contact_name: Chris Mungall
  context: '404'
  example: '0002533'
  message: HTTP 404
  name: Relation Ontology
  prefix: ro
  url: http://purl.obolibrary.org/obo/RO_0002533
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: doi
  message: HTTP 404
  name: Scholia Registry
  prefix: scholia.resource
  url: https://bioregistry.io/metaregistry/scholia/doi
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '47419'
  message: HTTP 404
  name: Structural Classification of Protein
  prefix: scop
  url: http://scop.mrc-lmb.cam.ac.uk/scop/search.cgi?sunid=47419
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''www.sigmaaldrich.com'', port=443): Read timed
    out. (read timeout=15)'
  example: HPA000698
  message: ReadTimeout
  name: Sigma Aldrich
  prefix: sigmaaldrich
  url: https://www.sigmaaldrich.com/US/en/product/sigma/HPA000698
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.signaling-gateway.org'', port=80): Max retries
    exceeded with url: /molecule/query?afcsid=A001094 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f3b2e80>: Failed to establish a new connection: [Errno 61] Connection
    refused''))'
  example: A001094
  message: ConnectionError
  name: Signaling Gateway
  prefix: signaling-gateway
  url: http://www.signaling-gateway.org/molecule/query?afcsid=A001094
- contact_email: sio-ontology@googlegroups.com
  contact_github: null
  contact_name: null
  context: '404'
  example: 000912
  message: HTTP 404
  name: Semanticscience Integrated Ontology
  prefix: sio
  url: https://www.ebi.ac.uk/ols/ontologies/sio/terms?short_form=000912
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''search.sisuproject.fi'', port=443): Max retries
    exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, ''[SSL: CERTIFICATE_VERIFY_FAILED]
    certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'')))'
  example: 17:41223048
  message: SSLError
  name: Sequencing Initiative Suomi
  prefix: sisu
  url: http://search.sisuproject.fi/#/variant/17:41223048
- contact_email: null
  contact_github: null
  contact_name: null
  context: '403'
  example: '1000'
  message: HTTP 403
  name: SitEx
  prefix: sitex
  url: http://www-bionet.sscc.ru/sitex/index.php?siteid=1000
- contact_email: null
  contact_github: null
  contact_name: null
  context: '406'
  example: '3618'
  message: HTTP 406
  name: SUM Breast Cancer Cell Line Knowledge Base
  prefix: slkbase
  url: https://sumlineknowledgebase.com/?page_id=3618
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPSConnectionPool(host=''ccg.epfl.ch'', port=443): Max retries exceeded
    with url: /cgi-bin/snp2tfbs/snpviewer_form_parser.cgi?snpid=rs11603840 (Caused
    by SSLError(SSLCertVerificationError(1, ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate
    verify failed: unable to get local issuer certificate (_ssl.c:1129)'')))'
  example: rs11603840
  message: SSLError
  name: SNP to Transcription Factor Binding Sites
  prefix: snp2tfbs
  url: https://ccg.epfl.ch/cgi-bin/snp2tfbs/snpviewer_form_parser.cgi?snpid=rs11603840
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.soybase.org'', port=80): Max retries exceeded
    with url: /sbt/search/search_results.php?category=SNP&search_term=BARC-013845-01256
    (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x11f2f7c40>:
    Failed to establish a new connection: [Errno 61] Connection refused''))'
  example: BARC-013845-01256
  message: ConnectionError
  name: Glycine max Genome Database
  prefix: soybase
  url: http://www.soybase.org/sbt/search/search_results.php?category=SNP&search_term=BARC-013845-01256
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''psb.kobic.re.kr'', port=80): Max retries exceeded
    with url: /STAP/refinement1/result.php?search=1a24 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f2eb340>, ''Connection to psb.kobic.re.kr timed out. (connect timeout=15)''))'
  example: 1a24
  message: ConnectTimeout
  name: Statistical Torsional Angles Potentials
  prefix: stap
  url: http://psb.kobic.re.kr/STAP/refinement1/result.php?search=1a24
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: P53350
  message: HTTP 404
  name: Search Tool for Retrieval of Interacting Genes/Proteins
  prefix: string
  url: http://string.embl.de/interactions/P53350
- contact_email: allyson.lister@oerc.ox.ac.uk
  contact_github: allysonlister
  contact_name: Allyson Lister
  context: '404'
  example: '0000144'
  message: HTTP 404
  name: Software ontology
  prefix: swo
  url: http://purl.obolibrary.org/obo/SWO_0000144
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '0221'
  message: HTTP 404
  name: Tohoku University cell line catalog
  prefix: tkg
  url: http://www2.idac.tohoku.ac.jp/dep/ccr/TKGdate/TKGvol08/0221.html
- contact_email: null
  contact_github: null
  contact_name: null
  context: '401'
  example: TB2:S1000
  message: HTTP 401
  name: TreeBASE
  prefix: treebase
  url: http://purl.org/phylo/treebase/phylows/study/TB2:S1000?format=html
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''bidd.nus.edu.sg'', port=80): Max retries exceeded
    with url: /group/TTD/ZFTTDDRUG.asp?ID=DAP000773 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f14ad60>, ''Connection to bidd.nus.edu.sg timed out. (connect timeout=15)''))'
  example: DAP000773
  message: ConnectTimeout
  name: TTD Drug
  prefix: ttd.drug
  url: http://bidd.nus.edu.sg/group/TTD/ZFTTDDRUG.asp?ID=DAP000773
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''bidd.nus.edu.sg'', port=80): Max retries exceeded
    with url: /group/TTD/ZFTTDDetail.asp?ID=TTDS00056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f2cb700>, ''Connection to bidd.nus.edu.sg timed out. (connect timeout=15)''))'
  example: TTDS00056
  message: ConnectTimeout
  name: TTD Target
  prefix: ttd.target
  url: http://bidd.nus.edu.sg/group/TTD/ZFTTDDetail.asp?ID=TTDS00056
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.ubio.org'', port=80): Max retries exceeded
    with url: /browser/details.php?namebankID=2555646 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f312670>, ''Connection to www.ubio.org timed out. (connect timeout=15)''))'
  example: '2555646'
  message: ConnectTimeout
  name: uBio NameBank
  prefix: ubio.namebank
  url: http://www.ubio.org/browser/details.php?namebankID=2555646
- contact_email: null
  contact_github: null
  contact_name: null
  context: No connection adapters were found for 'ftp://hgdownload.cse.ucsc.edu/goldenPath/uc001rvw.5'
  example: uc001rvw.5
  message: InvalidSchema
  name: UCSC Genome Browser
  prefix: ucsc
  url: ftp://hgdownload.cse.ucsc.edu/goldenPath/uc001rvw.5
- contact_email: null
  contact_github: null
  contact_name: null
  context: '410'
  example: '4900'
  message: HTTP 410
  name: UniGene
  prefix: unigene
  url: http://www.ncbi.nlm.nih.gov/UniGene/clust.cgi?UGID=4900
- contact_email: null
  contact_github: null
  contact_name: null
  context: '500'
  example: UPI000000000A
  message: HTTP 500
  name: UniProt Archive
  prefix: uniparc
  url: https://www.ebi.ac.uk/cgi-bin/dbfetch?db=uniparc&id=UPI000000000A
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.grenoble.prabi.fr'', port=80): Max retries
    exceeded with url: /obiwarehouse/unipathway/upc?upid=UPC04349 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f2d1760>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: UPC04349
  message: ConnectionError
  name: UniPathway Compound
  prefix: unipathway.compound
  url: http://www.grenoble.prabi.fr/obiwarehouse/unipathway/upc?upid=UPC04349
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www.grenoble.prabi.fr'', port=80): Max retries
    exceeded with url: /obiwarehouse/unipathway/ucr?upid=UCR00226 (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x11f2db610>: Failed to establish a new connection: [Errno 8] nodename
    nor servname provided, or not known''))'
  example: UCR00226
  message: ConnectionError
  name: UniPathway Reaction
  prefix: unipathway.reaction
  url: http://www.grenoble.prabi.fr/obiwarehouse/unipathway/ucr?upid=UCR00226
- contact_email: null
  contact_github: null
  contact_name: null
  context: '410'
  example: '456789'
  message: HTTP 410
  name: Database of Sequence Tagged Sites
  prefix: unists
  url: https://www.ncbi.nlm.nih.gov/genome/sts/sts.cgi?uid=456789
- contact_email: null
  contact_github: null
  contact_name: null
  context: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
  example: '4145692'
  message: ConnectionError
  name: United States Patent and Trademark Office
  prefix: uspto
  url: http://patft.uspto.gov/netacgi/nph-Parser?Sect2=PTO1&Sect2=HITOFF&p=1&u=/netahtml/PTO/search-bool.html&r=1&f=G&l=50&d=PALL&RefSrch=yes&Query=PN/4145692
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: '35742'
  message: HTTP 404
  name: Viral Bioinformatics Resource Center
  prefix: vbrc
  url: http://vbrc.org/gene_detail.asp?gene_id=35742
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: BeAn 70563
  message: HTTP 404
  name: Virus Pathogen Resource
  prefix: vipr
  url: http://www.viprbrc.org/brc/viprStrainDetails.do?strainName=BeAn 70563&decorator=arena
- contact_email: null
  contact_github: null
  contact_name: null
  context: '404'
  example: T01B6.1
  message: HTTP 404
  name: C. elegans ORFeome cloning project
  prefix: worfdb
  url: http://worfdb.dfci.harvard.edu/index.php?search_type=name&page=showresultrc&race_query=T01B6.1
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''www-deletion.stanford.edu'', port=80): Max retries
    exceeded with url: /cgi-bin/YDPM/YDPM_search.cgi?thelist=YAL001C (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f14a7f0>, ''Connection to www-deletion.stanford.edu timed out. (connect
    timeout=15)''))'
  example: YAL001C
  message: ConnectTimeout
  name: Yeast Deletion and the Mitochondrial Proteomics Project
  prefix: ydpm
  url: http://www-deletion.stanford.edu/cgi-bin/YDPM/YDPM_search.cgi?thelist=YAL001C
- contact_email: null
  contact_github: null
  contact_name: null
  context: 'HTTPConnectionPool(host=''metarray.ucsc.edu'', port=80): Max retries exceeded
    with url: /cgi-bin/intron/yirIntrondb?orfName=SNR17A (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection
    object at 0x11f2cbf10>, ''Connection to metarray.ucsc.edu timed out. (connect
    timeout=15)''))'
  example: SNR17A
  message: ConnectTimeout
  name: Yeast Intron Database v3
  prefix: yid
  url: http://metarray.ucsc.edu/cgi-bin/intron/yirIntrondb?orfName=SNR17A
